# home
root:
    path: /
    defaults:
        resource: "landing"
    methods: [GET, POST]
    
auth:
    path: /{resource}{slash}/{action}
    requirements:
        resource: "auth"
        slash: "[/]{0,1}"
    methods: [GET, POST, PUT, DELETE]